# generated by clj2nix-1.1.0-rc
{ fetchMavenArtifact, fetchgit, lib }:

let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/" ];

  in rec {
      makePaths = {extraClasspaths ? []}:
        if (builtins.typeOf extraClasspaths != "list")
        then builtins.throw "extraClasspaths must be of type 'list'!"
        else (lib.concatMap (dep:
          builtins.map (path:
            if builtins.isString path then
              path
            else if builtins.hasAttr "jar" path then
              path.jar
            else if builtins.hasAttr "outPath" path then
              path.outPath
            else
              path
            )
          dep.paths)
        packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}:
       if (builtins.typeOf extraClasspaths != "list")
       then builtins.throw "extraClasspaths must be of type 'list'!"
       else builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});
      packageSources = builtins.map (dep: dep.src) packages;
      packages = [
  rec {
    name = "transit-java/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-java";
      groupId = "com.cognitect";
      sha512 = "80365a4f244e052b6c4fdfd2fd3b91288835599cb4dd88e0e0dae19883dcda39afee83966810ed81beff342111c3a45a66f5601c443f3ad49904908c43631708";
      version = "0.8.332";
      
    };
    paths = [ src ];
  }

  rec {
    name = "elemental2-core/com.google.elemental2";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "elemental2-core";
      groupId = "com.google.elemental2";
      sha512 = "feac71c23abd3a3b02949d5844541490a9d6a6247b5707ca3791ef3cff93de09d712b1220e46a18b37b5bcfae5d93533fc59eaddeb7f4b8432b3a637f190f04d";
      version = "1.0.0-RC1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.json/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "data.json";
      groupId = "org.clojure";
      sha512 = "ce526bef01bedd31b772954d921a61832ae60af06121f29080853f7932326438b33d183240a9cffbe57e00dc3744700220753948da26b8973ee21c30e84227a6";
      version = "0.2.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clojure/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "4bb567b9262d998f554f44e677a8628b96e919bc8bcfb28ab2e80d9810f8adf8f13a8898142425d92f3515e58c57b16782cff12ba1b5ffb38b7d0ccd13d99bbc";
      version = "1.10.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-codec/commons-codec";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-codec";
      groupId = "commons-codec";
      sha512 = "8edecc0faf38e8620460909d8191837f34e2bb2ce853677c486c5e79bb79e88d043c3aed69c11f1365c4884827052ee4e1c18ca56e38d1a5bc0ce15c57daeee3";
      version = "1.10";
      
    };
    paths = [ src ];
  }

  rec {
    name = "error_prone_annotations/com.google.errorprone";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "error_prone_annotations";
      groupId = "com.google.errorprone";
      sha512 = "c9521d6b31c5dbf04b77f128ee568edfb0266c0e8d199e1050b32ff54493736d73721661f139d75da24f126c2e2dd0e851c0cf6e14e7302942be08f211f3c2b5";
      version = "2.3.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.specs.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "c1d2a740963896d97cd6b9a8c3dcdcc84459ea66b44170c05b8923e5fbb731b4b292b217ed3447bbc9e744c9a496552f77a6c38aea232e5e69f8faa627dea4b5";
      version = "0.2.56";
      
    };
    paths = [ src ];
  }

  rec {
    name = "spec.alpha/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "0740dc3a755530f52e32d27139a9ebfd7cbdb8d4351c820de8d510fe2d52a98acd6e4dfc004566ede3d426e52ec98accdca1156965218f269e60dd1cd4242a73";
      version = "0.2.194";
      
    };
    paths = [ src ];
  }

  rec {
    name = "animal-sniffer-annotations/org.codehaus.mojo";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "animal-sniffer-annotations";
      groupId = "org.codehaus.mojo";
      sha512 = "9e5e3ea9e06e0ac9463869fd0e08ed38f7042784995a7b50c9bfd7f692a53f0e1430b9e1367dc772d0d4eafe5fd2beabbcc60da5008bd792f9e7ec8436c0f136";
      version = "1.14";
      
    };
    paths = [ src ];
  }

  rec {
    name = "react-dom/cljsjs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "react-dom";
      groupId = "cljsjs";
      sha512 = "2e016de81494787520ede53665297b7215e5984e34ff6a960f8a2dd929ec11572b19d49c61c0ed43ef85e7f69dab7cb985958cacd50726c5b08659713d82e061";
      version = "18.0.0-rc.0-0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "json-simple/com.googlecode.json-simple";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "json-simple";
      groupId = "com.googlecode.json-simple";
      sha512 = "f8798bfbcc8ab8001baf90ce47ec2264234dc1da2d4aa97fdcdc0990472a6b5a5a32f828e776140777d598a99d8a0c0f51c6d0767ae1a829690ab9200ae35742";
      version = "1.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library";
      groupId = "org.clojure";
      sha512 = "4a29ae05212b508f3d4e2f5f63c542cec3fb7c0bfd0ef01718c56e0eee6798cd727b05d63af7a912bc20d7fc10e903458bce98915464e2170337151eab4ec633";
      version = "0.0-20191016-6ae1f72f";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clojurescript/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "clojurescript";
      groupId = "org.clojure";
      sha512 = "8a8ab25bc6e30afc892a7d7d0cb754af1fe6380b5fdc9b62289234338e87931f38f3b9f6003c95360849797827430d382ca4a21df6095e1eb23b0a3aa4df7257";
      version = "1.10.758";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsinterop-annotations/com.google.jsinterop";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jsinterop-annotations";
      groupId = "com.google.jsinterop";
      sha512 = "34330e368db2e5122350dcc9237711694e4ea03bbc315163ed5fd6fd8f649ddb2dbd1224b28207802603f869de61a15439924a1fef0e864abc134242d36e1ccb";
      version = "1.0.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-core/com.fasterxml.jackson.core";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "a1bd6c264b9ab07aad3d0f26b65757e35ff47904ab895bb7f997e3e1fd063129c177ad6f69876907b04ff8a43c6b1770a26f53a811633a29e66a5dce57194f64";
      version = "2.8.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "react/cljsjs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "react";
      groupId = "cljsjs";
      sha512 = "48b243e6d43b5bdfff3a7780d59e8783c4c788d50d31dfa9fa8a40016bd75542aef0953735cee2d7eef62a9eb2ec263a87e9f6a2223cbd19ba1dd988b5570fe4";
      version = "18.0.0-rc.0-0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library-third-party/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "google-closure-library-third-party";
      groupId = "org.clojure";
      sha512 = "5d1e7fdeb403f78af53023ae30fb61246bf55a4c8c097c77f5ae9784c299c927c3d3a1b63cb890e52f2f7b0eb5b01475f23e917865cfc5241d755a5d7a9f2801";
      version = "0.0-20191016-6ae1f72f";
      
    };
    paths = [ src ];
  }

  rec {
    name = "closure-compiler-externs/com.google.javascript";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "closure-compiler-externs";
      groupId = "com.google.javascript";
      sha512 = "1bdd38bed7188d33aa340c315c69a76dffd1161e86f7863ff023a6d06eccc36b282ca85f6a039dc62ccb318dc3561a6b49bfa79ad654bc5b4d29907aa6d72fa2";
      version = "v20200315";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javassist/org.javassist";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "javassist";
      groupId = "org.javassist";
      sha512 = "ad65ee383ed83bedecc2073118cb3780b68b18d5fb79a1b2b665ff8529df02446ad11e68f9faaf4f2e980065f5946761a59ada379312cbb22d002625abed6a4f";
      version = "3.18.1-GA";
      
    };
    paths = [ src ];
  }

  rec {
    name = "guava/com.google.guava";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "guava";
      groupId = "com.google.guava";
      sha512 = "429ceeec0350ba98e2b089b8b70ded2ec570c3a684894a7545d10592c1c7be42dacd1fad8b2cb9123aa3612575ce1b56e1bb54923443fc293f8e9adeac2762ee";
      version = "25.1-jre";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reagent/reagent";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "reagent";
      groupId = "reagent";
      sha512 = "f37fb230befa669ca89e218a769fb6c29444756d3a905ed9b497eda729ea9f55c3aa9416e5a064152db0e4507d19b8d9667ba5aadea3a2f20868a1a505ba0d19";
      version = "1.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "msgpack/org.msgpack";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "msgpack";
      groupId = "org.msgpack";
      sha512 = "a2741bed01f9c37ba3dbe6a7ab9ce936d36d4da97c35e215250ac89ac0851fc5948d83975ea6257d5dce1d43b6b5147254ecfb4b33f9bbdc489500b3ff060449";
      version = "0.6.12";
      
    };
    paths = [ src ];
  }

  rec {
    name = "j2objc-annotations/com.google.j2objc";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "j2objc-annotations";
      groupId = "com.google.j2objc";
      sha512 = "a4a0b58ffc2d9f9b516f571bcd0ac14e4d3eec15aacd6320a4a1a12045acce8c6081e8ce922c4e882221cedb2cc266399ab468487ae9a08124d65edc07ae30f0";
      version = "1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-clj/com.cognitect";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "transit-clj";
      groupId = "com.cognitect";
      sha512 = "ad838d9e5688c8cebe54972ad0c9a6db428ec1cece8c8b078e8e8d4b0c7870b328239d2bc9dd8fcbedcba56ca0de9afb5a0a843ff5f630dc039118de7eb45eba";
      version = "0.8.309";
      
    };
    paths = [ src ];
  }

  rec {
    name = "args4j/args4j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "args4j";
      groupId = "args4j";
      sha512 = "5f0651234c8f8b130fddb39fa832c6da47d3e21bc3434307554314c47e672c28d005c64e9effe85d552190cfc27966b1f005740ffd40b4e1bec2cb257d7feedb";
      version = "2.0.26";
      
    };
    paths = [ src ];
  }

  rec {
    name = "base/com.google.jsinterop";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "base";
      groupId = "com.google.jsinterop";
      sha512 = "7a52fd9332d122b48b4c2c7dd6db5781120ee3e5cd4f8e71381fc70522d6ecb56dfcf01dfe32df21d5d7b6e7cc7dee199d0b20b5b326656c43f90acbf570155f";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "checker-qual/org.checkerframework";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "checker-qual";
      groupId = "org.checkerframework";
      sha512 = "3c38b0b9e0bde464268cff5fdb1894a048240b039093ee3abe5b32976a22737d26b355f8793f630a7f0b319fdb019a6fcd9ee1d5219676f0f10c0b0f496b61b7";
      version = "2.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.reader/org.clojure";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.reader";
      groupId = "org.clojure";
      sha512 = "290a2d98b2eec08a8affc2952006f43c0459c7e5467dc454f5fb5670ea7934fa974e6be19f7e7c91dadcfed62082d0fbcc7788455b7446a2c9c5af02f7fc52b6";
      version = "1.3.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "re2j/com.google.re2j";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "re2j";
      groupId = "com.google.re2j";
      sha512 = "a9bd66b95ede4d7576358b974db8059eef884d0ce59a1e065a3be1e84b97f50af7bbc6429968750f82faab1e666bbb9e51f8685e12051bb5407b3943804f04f6";
      version = "1.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "closure-compiler-unshaded/com.google.javascript";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "closure-compiler-unshaded";
      groupId = "com.google.javascript";
      sha512 = "c12be8c6a61fd323ce0c9e6778de42564dbc938a577e576b0b4e6631c0ceb484a8332ff7fe8cf4abfbc72a9263b4205c1da363ba8cedf8c011d254f647908f4e";
      version = "v20200315";
      
    };
    paths = [ src ];
  }

  rec {
    name = "protobuf-java/com.google.protobuf";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "protobuf-java";
      groupId = "com.google.protobuf";
      sha512 = "8bfedb8fbc46a1f9d4408236a50d53cb71750a0680f351e26c4c238c15803ee7c180fad462e885129c60d3335f98a947b170a32704265044312b1ec5daa0003a";
      version = "3.11.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsr305/com.google.code.findbugs";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "jsr305";
      groupId = "com.google.code.findbugs";
      sha512 = "bb09db62919a50fa5b55906013be6ca4fc7acb2e87455fac5eaf9ede2e41ce8bbafc0e5a385a561264ea4cd71bbbd3ef5a45e02d63277a201d06a0ae1636f804";
      version = "3.0.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "gson/com.google.code.gson";
    src = fetchMavenArtifact {
      inherit repos;
      artifactId = "gson";
      groupId = "com.google.code.gson";
      sha512 = "c3cdaf66a99e6336abc80ff23374f6b62ac95ab2ae874c9075805e91d849b18e3f620cc202b4978fc92b73d98de96089c8714b1dd096b2ae1958cfa085715f7a";
      version = "2.7";
      
    };
    paths = [ src ];
  }

  ];
  }
  